[server]
host = "127.0.0.1"
port = 9000
compress_level = 1 # Docs: https://git.io/J3SRK
prefork = false # if true spacebin will run across multiple processes

[server.ratelimits]
requests = 80
duration = 60_000 # in ms

[database]
dialect = "sqlite" # possible: mysql, sqlite, postgresql
connection_uri = "/home/container/spacebin.db"

[documents]
id_length = 8
max_document_length = 400_000 # in bytes
max_age = 90 # in days
